apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: postgres-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi