apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: postgres-sc
provisioner: k8s.io/minikube-hostpath
parameters:
 {}
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false